apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: social-platform
type: Opaque
stringData:
  MONGO_URI: "mongodb+srv://ayushsakalkale30:responsive@cluster0.pxwjraa.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
  PORT: "3000"
  TOKEN_SECRET: "qwerty"
  CLOUDINARY_CLOUD_NAME: "dxpygdguo"
  CLOUDINARY_API_KEY: "275632115714873"
  CLOUDINARY_API_SECRET: "hiBU7ThK84T-6gVbZI9clI4lkFs"
  CLOUDINARY_URL: "cloudinary://275632115714873:hiBU7ThK84T-6gVbZI9clI4lkFs@dxpygdguo"
  USER_EMAIL: "ayushsakalkale@gmail.com"
  USER_EMAIL_PASSWORD: "ylir ngzh yogp fhpu"
  VITE_PORT: "5173"
